# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mobi"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jkongie"]
  s.date = "2013-10-04"
  s.description = "Mobi is a Rubygem that allows you to easily read MOBI e-book format metadata."
  s.email = "jkongie@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/mobi.rb",
    "lib/mobi/header/exth_header.rb",
    "lib/mobi/header/mobi_header.rb",
    "lib/mobi/header/palm_doc_header.rb",
    "lib/mobi/metadata.rb",
    "lib/mobi/metadata_streams.rb",
    "lib/mobi/stream_slicer.rb",
    "mobi.gemspec",
    "spec/fixtures/sherlock.mobi",
    "spec/lib/mobi/header/exth_header_spec.rb",
    "spec/lib/mobi/header/mobi_header_spec.rb",
    "spec/lib/mobi/header/palm_doc_header_spec.rb",
    "spec/lib/mobi/metadata_spec.rb",
    "spec/lib/mobi/stream_slicer_spec.rb",
    "spec/lib/mobi_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jkongie/mobi"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "A Rubygem that inspects MOBI metadata."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_development_dependency(%q<rr>, ["~> 1.0.4"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_dependency(%q<rr>, ["~> 1.0.4"])
      s.add_dependency(%q<bundler>, ["~> 1.3.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.14.0"])
    s.add_dependency(%q<rr>, ["~> 1.0.4"])
    s.add_dependency(%q<bundler>, ["~> 1.3.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.0"])
  end
end

